### ISSUE TITLE
Update Highcharts to newer version.

### ISSUE THREAD

**Issue by lucaSartore** [webix-hub/components#47]
I noted that your [highcharts integration](https://github.com/webix-hub/components/tree/master/highcharts) is stuck at version 7.2.0, despite the newer version being 11.3.0. I would need one of the latest highcharts features at work…
Judging by [this](https://github.com/webix-hub/components/commit/d4352a868ababf15faa8c7b0ee6d543dd0ae8c5a) commit, updating the version does not seem to be a big deal. Is it possible to get it updated?  
I may even do it myself, test it, and then open a PR if you tell me that there is a good chance that it will be merged.

**Comment by HelgaListopad** [comment]
Hi @lucaSartore 

Truly, we didn't update these integrations for a long time. Since they are intended as free examples without constant support, the updates usually come after a request/necessity.
We appreciate contributions to this repo, so yes, you are welcome to submit a PR, or we will update integration per your request within the next few days. 

Thank you for the suggestion!
